Algoritmo "contarAte0"
// Exercicio aula 9 | algoritmo | guanabara
// Contar ate de 10 a 0
Var
// Seção de Declarações das variáveis 
n : inteiro
m : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreval("CONTADOR REGRESSIVO")
    
    n <- 10
    
    Enquanto (n >= 0) faca
       Escreval(n)
       n <- n - 1
    FimEnquanto
    
    m <- "FELIZ ANO NOVO"
    Escreva(m)

Fimalgoritmo