Algoritmo "contarAte10"
// Aula 9 |  Algoritmo | GUANABARA
// Contar de 0 - 10
Var
// Seção de Declarações das variáveis 
n : inteiro

Inicio
// testando looping
   n <- 0
   
   // enquanto uma expressao for true - ele repetirá o bloco
   Enquanto (n <= 10 )faça
   
             Escreval(n)
             n <- n + 1

   //quando o bloco passar por todas as verificações e não tiver + validação
   //a linha abaixo é executada
   FimEnquanto
   
   Escreva("contou até ", n - 1)

Fimalgoritmo