Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/09/2022
Var
// Seção de Declarações das variáveis 
c, n, s : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     c <- 0
     s <- 0
     
     Escreva("Somador")
     


Fimalgoritmo